language: objective-c
sudo: false
xcode_project: FoundationExtension.xcodeproj
osx_image: xcode9.4
matrix:
  include:
    - osx_image: xcode10
      xcode_sdk: macosx
      xcode_scheme: CocoaExtension
      xcode_destination: platform=macOS
    - osx_image: xcode10
      xcode_sdk: iphonesimulator
      xcode_scheme: UIKitExtension
      xcode_destination: platform=iOS Simulator,OS=11.3,name=iPhone X
    - osx_image: xcode10
      xcode_sdk: appletvsimulator
      xcode_scheme: UIKitExtension
      xcode_destination: platform=tvOS Simulator,OS=11.3,name=Apple TV 4K
    - osx_image: xcode7  # legacy support
      xcode_scheme: CocoaExtension
      xcode_destination: platform=macOS
  allow_failures:
    - xcode_sdk: appletvsimulator
